SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING(ANIMAL_ID, ANIMAL_TYPE, NAME)
ORDER BY TIMESTAMPDIFF(DAY, I.DATETIME, O.DATETIME ) DESC
LIMIT 2


/*
ANIMAL_ID	NAME
A362707	Girly Girl
A370507	Emily
*/