SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM(
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
           ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS TYPE_FAV_RANK
    FROM REST_INFO) AS INLINEVIEW
WHERE TYPE_FAV_RANK = 1
ORDER BY FOOD_TYPE DESC

/*
FOOD_TYPE	REST_ID	REST_NAME	FAVORITES
한식	00001	은돼지식당	734
중식	00015	만정	20
일식	00004	스시사카우스	230
양식	00003	따띠따띠뜨	102
분식	00008	애플우스	151
*/

