SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, 
       COUNT(DISTINCT USER_ID) AS PUCHASED_USERS, 
       ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(DISTINCT USER_ID) 
                             FROM USER_INFO 
                             WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO LEFT JOIN ONLINE_SALE  USING(USER_ID)
WHERE YEAR(JOINED) = 2021 AND ONLINE_SALE_ID IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# SELECT YEAR(SALES_DATE) AS YEAR,
#        MONTH(SALES_DATE) AS MONTH,
#        COUNT(DISTINCT(a.USER_ID)) AS PUCHASED_USERS,
#        ROUND(COUNT(DISTINCT a.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) 
#                                           FROM USER_INFO 
#                                           WHERE YEAR(JOINED) = 2021) , 1) AS PUSHASED_RATIO
# FROM USER_INFO AS a INNER JOIN ONLINE_SALE AS b USING(USER_ID)
# WHERE YEAR(JOINED) = 2021
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY 1 ASC, 2 ASC