SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL
FROM FOOD_ORDER JOIN FOOD_PRODUCT USING(PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL DESC, PRODUCT_ID ASC