WITH RENTAL_PERIOD AS ( #⭐ 대여 기간 계산
SELECT *, TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1 AS RENTAL_DATE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
), EXACT_DURATION_TYPE AS( #⭐  계산된 대여 기간을 통해 기간 타입 정하기
     SELECT *, CASE 
                 WHEN RENTAL_DATE < 7 THEN NULL
                 WHEN RENTAL_DATE < 30 THEN '7일 이상'
                 WHEN RENTAL_DATE < 90 THEN '30일 이상'
                 ELSE '90일 이상' 
               END AS R_DURATION_TYPE
    FROM RENTAL_PERIOD
), EXTRACTING_DURATION_RATE AS ( #⭐  정해진 기간 타입으로 할인율 구하기 
        SELECT E.CAR_TYPE, HISTORY_ID, RENTAL_DATE, DAILY_FEE, 
               COALESCE(DISCOUNT_RATE, 0) AS DISCOUNT_RATE 
        FROM EXACT_DURATION_TYPE E LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
             ON E.CAR_TYPE = P.CAR_TYPE AND R_DURATION_TYPE = DURATION_TYPE
        GROUP BY HISTORY_ID
)

 
SELECT HISTORY_ID, TRUNCATE( RENTAL_DATE * DAILY_FEE * (1 - DISCOUNT_RATE / 100), 0) AS FEE 
FROM EXTRACTING_DURATION_RATE
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC


/*
HISTORY_ID	FEE
724	6336960
681	5356240
630	4791360
...
711	107000
705	107000
627	107000
524	107000

*/