SELECT FLAVOR
FROM (SELECT * FROM FIRST_HALF
      UNION ALL
      SELECT * FROM JULY) AS INLINE
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
  
/*
FLAVOR
strawberry
chocolate
white_chocolate
*/