SELECT HOUR, COALESCE(COUNT, 0, 1) 
FROM (SELECT ROW_NUMBER() OVER () -1 AS HOUR
                       FROM ANIMAL_OUTS 
                       LIMIT 24) AS A
LEFT JOIN (
SELECT HOUR(DATETIME) HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)) AS B USING(HOUR)


