SELECT WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC

/*
WRITER_ID	NICKNAME	TOTAL_SALES
zkzkdh1	후후후	700000
dhfkzmf09	찐찐	860000
sangyoung58	보라보라	1500000
*/