# SELECT MEMBER_NAME, REVIEW_TEXT, 
#        DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE JOIN REST_REVIEW USING (MEMBER_ID)
# WHERE MEMBER_ID IN (SELECT MEMBER_ID
#                     FROM (SELECT *, DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS REVIEW_RANK
#                           FROM REST_REVIEW 
#                           GROUP BY MEMBER_ID) INLINE
#                     WHERE REVIEW_RANK = 1
#                    )
# ORDER BY REVIEW_DATE, REVIEW_TEXT


# SELECT *
# FROM (

# ) INLINE JOIN MEMBER_PROFILE USING(MEMBER_ID)

WITH REST_REVIEW_WITH_COUNT AS (
SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE,
COUNT(*) OVER (PARTITION BY MEMBER_ID) AS REVIEW_COUNT
FROM REST_REVIEW 
)

SELECT MEMBER_NAME, REVIEW_TEXT, 
       DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW_WITH_COUNT JOIN MEMBER_PROFILE USING(MEMBER_ID) 
WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT)
                      FROM REST_REVIEW_WITH_COUNT)
ORDER BY REVIEW_DATE, REVIEW_TEXT
