# SELECT MEMBER_NAME, REVIEW_TEXT, 
#        DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE JOIN REST_REVIEW USING (MEMBER_ID)
# WHERE MEMBER_ID IN (SELECT MEMBER_ID
#                     FROM (SELECT *, DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS REVIEW_RANK
#                           FROM REST_REVIEW 
#                           GROUP BY MEMBER_ID) INLINE
#                     WHERE REVIEW_RANK = 1
#                    )
# ORDER BY REVIEW_DATE, REVIEW_TEXT


SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE,
COUNT(MEMBER_ID) OVER (PARTITION BY MEMBER_ID) AS REVIEW_COUNT
FROM REST_REVIEW 
ORDER BY REVIEW_COUNT DESC