/*
SHIPMENT_ID	FLAVOR	TOTAL_ORDER
104	caramel	2600
101	chocolate	3200
*/
/*
FLAVOR	INGREDIENT_TYPE
caramel	sugar_based
chocolate	sugar_based
*/

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC

/*
INGREDIENT_TYPE	TOTAL_ORDER
sugar_based	13400
fruit_based	5550
*/