SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF JOIN ICECREAM_INFO USING(FLAVOR)
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC

/*
INGREDIENT_TYPE	TOTAL_ORDER
fruit_based	5550
sugar_based	13400
*/