SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE ('2022-01%')
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
/*
CATEGORY	TOTAL_SALES
경제	101
기술	151
생활	86
소설	60
인문	51
*/