SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN('과자', '국', '김치', '식용유')
      AND
      PRICE IN (SELECT MAX(PRICE) OVER(PARTITION BY CATEGORY)
                FROM FOOD_PRODUCT) 
ORDER BY PRICE DESC

/*
CATEGORY	PRICE	PRODUCT_NAME
김치	16950	맛있는백김치
식용유	4880	맛있는콩기름
국	2400	맛있는미역국
과자	1500	맛있는포카칩
*/