SELECT BOOK_ID, AUTHOR_NAME, 
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK JOIN AUTHOR USING(AUTHOR_ID)
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC

/*
BOOK_ID	AUTHOR_NAME	PUBLISHED_DATE
1	홍길동	2020-01-10
2	홍길동	2021-06-10
*/